# Generated by Django 3.0.2 on 2020-01-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QQMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=32)),
                ('user_id', models.IntegerField()),
                ('content', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=16)),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'qq_message',
            },
        ),
    ]
