# Generated by Django 3.0.2 on 2020-01-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqmessage',
            name='user_id',
            field=models.IntegerField(max_length=16),
        ),
    ]
