# Generated by Django 3.0.2 on 2020-01-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0002_auto_20200122_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqmessage',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
