# Generated by Django 3.0.2 on 2020-01-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0003_auto_20200122_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqmessage',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='qqmessage',
            name='user_id',
            field=models.CharField(max_length=32),
        ),
    ]
