# Generated by Django 3.0.2 on 2020-08-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0004_auto_20200122_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilibiliSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=32)),
                ('group_id', models.CharField(max_length=32)),
                ('bilibili_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'bilibili_subscription',
            },
        ),
    ]
