# Generated by Django 3.0.2 on 2020-08-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0005_bilibilisubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bilibilisubscription',
            unique_together={('user_id', 'group_id', 'bilibili_id')},
        ),
    ]
