# Generated by Django 3.1 on 2020-10-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0006_auto_20200826_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('singer', models.CharField(max_length=32)),
                ('lyric', models.CharField(max_length=4096)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
