# Generated by Django 3.1 on 2020-10-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ywwuyi', '0007_lyric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lyric',
            table='mqmmw_lyric',
        ),
    ]
