"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os, sys
from django.contrib import admin
from django.contrib.admin.apps import AdminConfig

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# /mqmmw
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# /mqmmw/apps
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# /mqmmw/templates
TEMPLATES_DIR = os.path.join( PROJECT_DIR , 'templates')
# 临时文件目录
TMP_DIR = os.path.join( PROJECT_DIR , 'tmp')

# 将apps加入环境变量
# 1.使INSTALLED_APPS能够引用ywwuyi.apps.ywwuyiConfig，而不用apps.ywwuyi.apps.ywwuyiConfig
# 2.使ywwuyi.apps.ywwuyiConfig中的name = 'ywwuyi'，而不用name = 'apps.ywwuyi'
sys.path.append(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&6flvs4%g4r#1&3rn=0usv8f_gfs)p^+paezw#c9tyq0^1&mdu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'channels',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ywwuyi.apps.ywwuyiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#url路由的入口
ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ TEMPLATES_DIR, ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mqmmw',
        'USER': 'root',
        'PASSWORD': 'Ijie8jKJi2demHU8ier',
        'HOST': '127.0.0.1',
        'PORT': 55506,
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

# internationalization
USE_I18N = False

# localization
USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(PROJECT_DIR, "public", "static")
STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "public", "static")
]

# routing的入口
ASGI_APPLICATION = 'apps.routing.application'

#redis
REDIS_IP="127.0.0.1"
REDIS_PORT="6379"
REDIS_PASSWD="qftal233"
